application:
  id: io-df-henry-arc-sample-api
  version: 1.0

spring:
  application:
    nameio-df-henry-arc-sample-api
  profiles:
    active: local

logging:
  level:
    root: DEBUG

server:
  port: 8080